imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    contact_email: info@diphda.net
    administration_email: info@diphda.net
    domain: http://ateneux.ll

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        real_course: '@AppBundle\Service\RealCourse'
        domain: '%domain%'
        contact_email: '%contact_email%'

# Doctrine Configuration
doctrine:
    dbal:
        server_version: 9.4
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.root_dir%/../web'
                cache_prefix: media/cache
    loaders:
        default:
            filesystem:
                data_root: '%kernel.root_dir%/../web/'

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    filter_sets:
        image_ig:
            quality: 100
            filters:
                interlace:
                    mode: line
                strip: ~
                relative_resize: { increase: 400 }
                crop: { start: [0, 50], size: [700, 420] }
        image_student_card:
                    quality: 100
                    filters:
                        interlace:
                            mode: line
                        strip: ~
                        thumbnail: { allow_upscale: true, size: [290, 200], mode: outbound }
        image_post_snippet_show:
                    quality: 100
                    filters:
                        interlace:
                            mode: line
                        strip: ~
                        thumbnail: { allow_upscale: true, size: [600, 1450], mode: inset }
        thumb_blog_article_main:
                    quality: 100
                    filters:
                        interlace:
                            mode: line
                        strip: ~
                        thumbnail: { allow_upscale: true, size: [701, 433], mode: outbound }
        thumb_latest_post:
                    quality: 100
                    filters:
                        interlace:
                            mode: line
                        strip: ~
                        thumbnail: { allow_upscale: true, size: [81, 81], mode: crop }
        image_task_big:
            quality: 100
            filters:
                interlace:
                    mode: line
                strip: ~
                thumbnail: { allow_upscale: true, size: [700,420], mode: outbound }
knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/xvfb-run wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/bin/xvfb-run wkhtmltoimage
        options:    []
easy_admin:
        entities:
            - AppBundle\Entity\Course
            - AppBundle\Entity\Student