<?php

namespace AppBundle\Entity;

/**
 * AcademicInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademicInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
