<?php

namespace AppBundle\Entity;

/**
 * AcademicInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademicInformationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRealInformation(Student $student)
    {
        $em = $this->getEntityManager();
        $dql = "select t from AppBundle:AcademicInformation t where t.student=:student ORDER BY  t.date DESC";

        $query = $em->createQuery($dql);
        $query->setParameter("student", $student);

        return $query->getResult();
    }
}
