<?php

namespace AppBundle\Entity;

/**
 * AssessmentBoardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentBoardRepository extends \Doctrine\ORM\EntityRepository
{
}
