<?php

namespace AppBundle\Entity;

/**
 * AssessmentBoardLearningDifficultiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentBoardLearningDifficultiesRepository extends \Doctrine\ORM\EntityRepository
{
}
