<?php

namespace AppBundle\Entity;

/**
 * AssessmentBoardLearningDifficultiesTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentBoardLearningDifficultiesTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
