<?php

namespace AppBundle\Entity;

/**
 * AssessmentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
