<?php

namespace AppBundle\Entity;

/**
 * CourseStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
