<?php

namespace AppBundle\Entity;

/**
 * GuidanceFollowUpFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuidanceFollowUpFileRepository extends \Doctrine\ORM\EntityRepository
{
}
