<?php

namespace AppBundle\Entity;

/**
 * GuidanceFollowUpStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuidanceFollowUpStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
