<?php

namespace AppBundle\Entity;

/**
 * MajorOffenceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MajorOffenceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
