<?php

namespace AppBundle\Entity;

/**
 * MediationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediationRepository extends \Doctrine\ORM\EntityRepository
{
}
