<?php

namespace AppBundle\Entity;

/**
 * MeetingTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
