<?php

namespace AppBundle\Entity;

/**
 * MeetingBoardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingBoardRepository extends \Doctrine\ORM\EntityRepository
{
}
