<?php

namespace AppBundle\Entity;

/**
 * MeetingStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
