<?php

namespace AppBundle\Entity;

/**
 * PenaltyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PenaltyTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
