<?php

namespace AppBundle\Entity;

/**
 * ProceduralTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProceduralTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
