<?php

namespace AppBundle\Entity;

/**
 * SchoolYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolYearRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRealSchoolCourse()
    {
        $em = $this->getEntityManager();
        $dql = "select s from AppBundle:SchoolYear s order by s.id desc";

        $query = $em->createQuery($dql);
        $query->setMaxResults(1);

        return $query->getSingleResult();

    }
}
