<?php

namespace AppBundle\Entity;

/**
 * StudentFamiliarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentFamiliarRepository extends \Doctrine\ORM\EntityRepository
{
}
