<?php

namespace AppBundle\Entity;

/**
 * StudentMedicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentMedicalRepository extends \Doctrine\ORM\EntityRepository
{
}
