<?php

namespace AppBundle\Entity;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{

    public function findMeetings($student_id, $meeting_status_id = null)
    {

        $em = $this->getEntityManager();
        $dql = "select t from AppBundle:Meeting t where t.student_meeting=:student ";
        if ($meeting_status_id) {
            $dql .= " and t.meeting_status=:status ";
        }

        $query = $em->createQuery($dql);
        $query->setParameter("student", $student_id);
        if ($meeting_status_id) {
            $query->setParameter("status", $meeting_status_id);
        }


        return $query->getResult();
    }

    public function findWarnings($student_id, $meeting_status_id = null)
    {

        $em = $this->getEntityManager();
        $dql = "select t from AppBundle:Warning t where t.student=:student ";

        $query = $em->createQuery($dql);
        $query->setParameter("student", $student_id);

        return $query->getResult();
    }

    public function findByUnity($course)
    {
        $em = $this->getEntityManager();
        $dql = "select t from AppBundle:Student t where t.course is null and t.course_type=:course_type ";
        $query = $em->createQuery($dql);
        $query->setParameter("course_type", $course->getCourseType());
        return $query->getResult();
    }


    public function getDifficulties($course, $student, $assessment_board)
    {
        $em = $this->getEntityManager();
        $dql = "select t from AppBundle:AssessmentBoardLearningDifficulties t where t.course=:course and t.student=:student and t.assessment_board=:assessment_board";
        $query = $em->createQuery($dql);
        $query->setParameter("course", $course);
        $query->setParameter("assessment_board", $assessment_board);
        $query->setParameter("student", $student);
        return $query->getResult();
    }

    public function findStudentAssessmentBoardCourse($assessmentBoard)
    {
        $em = $this->getEntityManager();
        $dql = "select t from AppBundle:Student t where t.course=:course order by t.surname, t.name";
        $query = $em->createQuery($dql);
        $query->setParameter("course", $assessmentBoard->getCourse());

        return $query->getResult();
    }

    public function findAllSorted()
    {
        $em = $this->getEntityManager();
        $dql = "select t from AppBundle:Student t order by t.surname, t.name";
        $query = $em->createQuery($dql);

        return $query->getResult();

    }

    public function findAllActiveSorted()
    {
        $em = $this->getEntityManager();
        $dql = "select t from AppBundle:Student t where t.course is not null order by t.surname, t.name";
        $query = $em->createQuery($dql);

        return $query->getResult();

    }
}
