<?php

namespace AppBundle\Entity;

/**
 * StudentschoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentSchoolRepository extends \Doctrine\ORM\EntityRepository
{
}
