<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
  public function findAllByStatus($status=null)
  {
    $em=$this->getEntityManager();
    $dql = 'SELECT u
        FROM AppBundle:UserProfile u';
    if ($status)
    {
      $dql.=' where u.status=:status';
    }
    $query = $em->createQuery($dql);
    if ($status)
    {
      $query->setParameter("status", $status);
    }

    return $query->getResult();
  }

  

  public function findByRole($role) {

    $query=$this->queryByRole($role);

    return $query->getResult();
  }

  
  public function queryByRole($role)
  {
    $em=$this->getEntityManager();
    $dql="SELECT u FROM AppBundle:User u WHERE u.roles LIKE :role";
    $query = $em->createQuery($dql);
    $query->setParameter('role', '%' . $role . '%');
    
    return $query;
  }
  /**
   * Esta función es para el formulario de nuevo viaje, para que devuelva sólo los responsables y el admin
   * @return \Doctrine\ORM\QueryBuilder
   */
  public function getManagers()
  {
    $em=$this->getEntityManager();
    $qb = $this->_em->createQueryBuilder();
    $qb->select('u')
    ->from($this->_entityName, 'u')
    ->where('u.roles LIKE :roles')
    ->orWhere('u.roles LIKE :roles2')
    ->setParameter('roles', '%"' . 'ROLE_MANAGER' . '"%')
    ->setParameter('roles2', '%"' . 'ROLE_ADMIN' . '"%');

    return $qb;
  }
  
  
  //busca email repetidos
  public function findEmailCreated($email)
  {
    $em=$this->getEntityManager();
    $dql="SELECT u FROM AppBundle:User u WHERE u.email LIKE :email";
    $query = $em->createQuery($dql);
    $query->setParameter('email', $email);
    
    return $query->getOneOrNullResult(); 
  }
}
