<?php

namespace AppBundle\Entity;

/**
 * WarningTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarningTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
