<?php

namespace AppBundle\Entity;

/**
 * WarningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarningRepository extends \Doctrine\ORM\EntityRepository
{
}
