<?php

namespace AppBundle\Entity;

/**
 * WarningCauseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarningCauseTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
