<?php

namespace AppBundle\Entity;

use AppBundle\Service\RealCourse;

/**
 * WarningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarningRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param null $year
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByTypeYear($type, $year = null, $course = null, $course_type = null)
    {
        $em = $this->getEntityManager();
        $dql = "select count(w) as total from AppBundle:Warning w where w.date 
          BETWEEN :start and :end and w.warning_type=:type";
        if ($course) {
            $dql .= ' and w.course=:course ';
        }
        if ($course_type) {
            $dql .= ' and w.course_type=:course_type ';
        }

        $query = $em->createQuery($dql);
        $query->setParameter('type', $type);
        if ($course) {
            $query->setParameter("course", $course);
        }

        if ($course_type) {
            $query->setParameter("course_type", $course_type);
        }
        $query->setParameter('start', RealCourse::getStartDateCourse($year));
        $query->setParameter('end', RealCourse::getEndDateCourse($year));

        return $query->getSingleScalarResult();
    }

    /**
     * Para los cursos que ya se han finalizado, hago la consulta de otra manera
     * @param $type
     * @param $course
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByTypeCourse($type, $course)
    {
        $em = $this->getEntityManager();
        $dql = "select count(w) as total from AppBundle:Warning w where w.warning_type=:type and w.course=:course ";



        $query = $em->createQuery($dql);
        $query->setParameter('type', $type);
        if ($course) {
            $query->setParameter("course", $course);
        }



        return $query->getSingleScalarResult();
    }

    public function findByCourseTypeMonth($type, $month, $year = null, $course = null, $course_type=null)
    {
        $em = $this->getEntityManager();
        $dql = "select count(w) from AppBundle:Warning w
               where w.date 
          BETWEEN :start and :end 
              and MONTH(w.date)=:month and w.warning_type=:type 
              ";
        if ($course) {
            $dql .= ' and w.course=:course ';
        }
        if ($course_type) {
            $dql .= ' and w.course_type=:course_type ';
        }
        $dql .= ' order by w.date asc ';

        $query = $em->createQuery($dql);
        $query->setParameter('type', $type);
        $query->setParameter("month", $month);
        if ($course) {
            $query->setParameter("course", $course);
        }
        if ($course_type) {
            $query->setParameter("course_type", $course_type);
        }
        $query->setParameter('start', RealCourse::getStartDateCourse($year));
        $query->setParameter('end', RealCourse::getEndDateCourse($year));

        return $query->getSingleScalarResult();
    }


    public function findMajorOffenceByTypeYear($major_offence_type, $year = null, $course = null, $course_type=null)
    {
        $em = $this->getEntityManager();
        $dql = "select count(w) as total from AppBundle:Warning w where w.warning_type=:type and w.major_offence_type=:major_offence_type";

        if ($course==null or $course->getCourseStatus()->getId()==1)
        {
            $dql .=' and w.date 
          BETWEEN :start and :end ';
        }

        if ($course) {
            $dql .= ' and w.course=:course ';
        }
        if ($course_type) {
            $dql .= ' and w.course_type=:course_type ';
        }
        $query = $em->createQuery($dql);
        $query->setParameter('type', 2);
        if ($course) {
            $query->setParameter("course", $course);
        }
        if ($course_type) {
            $query->setParameter("course_type", $course_type);
        }
        $query->setParameter('major_offence_type', $major_offence_type);


        if ($course==null or $course->getCourseStatus()->getId()==1) {
            $query->setParameter('start', RealCourse::getStartDateCourse($year));
            $query->setParameter('end', RealCourse::getEndDateCourse($year));

        }
        return $query->getSingleScalarResult();
    }

    public function findMajorOffenceByCourseTypeMonth($major_offence_type, $month, $year = null, $course = null, $course_type=null)
    {
        $em = $this->getEntityManager();
        $dql = "select count(w) from AppBundle:Warning w
               where MONTH(w.date)=:month and w.warning_type=:type and w.major_offence_type=:major_offence_type
              ";

        if ($course==null or $course->getCourseStatus()->getId()==1)
        {
            $dql .=' and w.date 
          BETWEEN :start and :end ';
        }

        if ($course) {
            $dql .= ' and w.course=:course ';
        }
        if ($course_type) {
            $dql .= ' and w.course_type=:course_type ';
        }
        $dql .= ' order by w.date asc ';

        $query = $em->createQuery($dql);
        $query->setParameter('type', 2);
        if ($course) {
            $query->setParameter("course", $course);
        }
        if ($course_type) {
            $query->setParameter("course_type", $course_type);
        }
        $query->setParameter('major_offence_type', $major_offence_type);
        $query->setParameter("month", $month);

        if ($course==null or $course->getCourseStatus()->getId()==1) {
            $query->setParameter('start', RealCourse::getStartDateCourse($year));
            $query->setParameter('end', RealCourse::getEndDateCourse($year));
        }

        return $query->getSingleScalarResult();
    }

    public function findPenaltyByTypeYear($penalty_type, $year = null, $course = null, $course_type=null)
    {
        $em = $this->getEntityManager();
        $dql = "select count(w) as total from AppBundle:Warning w where  w.warning_type=:type and w.penalty_type=:penalty_type";

        if ($course==null or $course->getCourseStatus()->getId()==1)
        {
            $dql .=' and w.date 
          BETWEEN :start and :end ';
        }

        if ($course) {
            $dql .= ' and w.course=:course ';
        }
        if ($course_type) {
            $dql .= ' and w.course_type=:course_type ';
        }
        $query = $em->createQuery($dql);
        $query->setParameter('type', 2);
        if ($course) {
            $query->setParameter("course", $course);
        }
        if ($course_type) {
            $query->setParameter("course_type", $course_type);
        }

        $query->setParameter('penalty_type', $penalty_type);

        if ($course==null or $course->getCourseStatus()->getId()==1) {
            $query->setParameter('start', RealCourse::getStartDateCourse($year));
            $query->setParameter('end', RealCourse::getEndDateCourse($year));
        }

        return $query->getSingleScalarResult();
    }

    public function findPenaltyByCourseTypeMonth($penalty_type, $month, $year = null, $course = null, $course_type=null)
    {
        $em = $this->getEntityManager();
        $dql = "select count(w) from AppBundle:Warning w
               where  MONTH(w.date)=:month and w.warning_type=:type and w.penalty_type=:penalty_type
             ";

        if ($course==null or $course->getCourseStatus()->getId()==1)
        {
            $dql .=' and w.date 
          BETWEEN :start and :end ';
        }

        if ($course) {
            $dql .= ' and w.course=:course ';
        }
        if ($course_type) {
            $dql .= ' and w.course_type=:course_type ';
        }
        $dql .= ' order by w.date asc ';

        $query = $em->createQuery($dql);
        $query->setParameter('type', 2);
        if ($course) {
            $query->setParameter("course", $course);
        }
        if ($course_type) {
            $query->setParameter("course_type", $course_type);
        }
        $query->setParameter('penalty_type', $penalty_type);
        $query->setParameter("month", $month);

        if ($course==null or $course->getCourseStatus()->getId()==1) {
            $query->setParameter('start', RealCourse::getStartDateCourse($year));
            $query->setParameter('end', RealCourse::getEndDateCourse($year));
        }
        return $query->getSingleScalarResult();
    }

    public function findByTypeLevelYear($course_type_id, $warning_type, $year = null)
    {
        $em = $this->getEntityManager();
        $dql = "select count(w) as total from AppBundle:Warning w where w.date 
          BETWEEN :start and :end and w.warning_type=:warning_type
           and w.course_type=:course_type
          ";


        $query = $em->createQuery($dql);
        $query->setParameter('warning_type', $warning_type);

        $query->setParameter('course_type', $course_type_id);
        $query->setParameter('start', RealCourse::getStartDateCourse($year));
        $query->setParameter('end', RealCourse::getEndDateCourse($year));

        return $query->getSingleScalarResult();
    }


    public function findByTypeLevelYearMonth($course_type_id, $warning_type, $month, $year = null)
    {
        $em = $this->getEntityManager();
        $dql = "select count(w) as total from AppBundle:Warning w where w.date 
          BETWEEN :start and :end and MONTH(w.date)=:month and w.warning_type=:warning_type
           and w.course_type=:course_type
          ";


        $query = $em->createQuery($dql);
        $query->setParameter('warning_type', $warning_type);

        $query->setParameter('course_type', $course_type_id);
        $query->setParameter("month", $month);
        $query->setParameter('start', RealCourse::getStartDateCourse($year));
        $query->setParameter('end', RealCourse::getEndDateCourse($year));

        return $query->getSingleScalarResult();
    }


    public function findMajorOffenceByTypeYearLevel($major_offence_type, $course_type_id, $year = null, $course = null)
    {
        $em = $this->getEntityManager();
        $dql = "select count(w) as total from AppBundle:Warning w where w.date 
          BETWEEN :start and :end and w.warning_type=:type and w.major_offence_type=:major_offence_type and w.course_type=:course_type";
        if ($course) {
            $dql .= ' and w.course=:course ';
        }
        $query = $em->createQuery($dql);
        $query->setParameter('type', 2);
        if ($course) {
            $query->setParameter("course", $course);
        }
        $query->setParameter('course_type', $course_type_id);
        $query->setParameter('major_offence_type', $major_offence_type);
        $query->setParameter('start', RealCourse::getStartDateCourse($year));
        $query->setParameter('end', RealCourse::getEndDateCourse($year));

        return $query->getSingleScalarResult();
    }

    public function findPenaltyByTypeYearLevel($penalty_type, $course_type_id, $year = null, $course = null)
    {
        $em = $this->getEntityManager();
        $dql = "select count(w) as total from AppBundle:Warning w where w.date 
          BETWEEN :start and :end and w.warning_type=:type and w.penalty_type=:penalty_type  and w.course_type=:course_type ";
        if ($course) {
            $dql .= ' and w.course=:course ';
        }

        $query = $em->createQuery($dql);
        $query->setParameter('type', 2);
        if ($course) {
            $query->setParameter("course", $course);
        }
        $query->setParameter('penalty_type', $penalty_type);
        $query->setParameter('course_type', $course_type_id);
        $query->setParameter('start', RealCourse::getStartDateCourse($year));
        $query->setParameter('end', RealCourse::getEndDateCourse($year));

        return $query->getSingleScalarResult();
    }

    public function findWarningByStudentCourse($course)
    {
        $em = $this->getEntityManager();
        $dql = "select count(w) as total, IDENTITY(w.student) as s from AppBundle:Warning w where w.course=:course group by s order by total desc";
        $query = $em->createQuery($dql);
        $query->setParameter("course", $course);

        return $query->getResult();
    }

}
